version: '3'

services:
  python:
    container_name: python
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8000:8000"
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./python:/usr/src/app/
    networks:
      - mynetwork
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
